# Generated by Django 4.1.7 on 2023-03-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "thumbnail_sizes",
                    models.CharField(
                        default="200",
                        help_text="Comma-separated list of thumbnail sizes",
                        max_length=64,
                    ),
                ),
                ("include_original_link", models.BooleanField(default=False)),
                ("generate_expiring_link", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.accounttier",
            ),
        ),
    ]
